// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;

    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRODr13uIfCDztnEX0gKJNUcYP6muEuhk',
    appId: '1:671942974107:android:11f8645560dae58519443e',
    messagingSenderId: '671942974107',
    projectId: 'ques-9e59f',
    storageBucket: 'ques-9e59f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ViflUqTmBfguEU_gYH1oBBqyRA0LX6Q',
    appId: '1:671942974107:ios:a28ca4872ffe1ccb19443e',
    messagingSenderId: '671942974107',
    projectId: 'ques-9e59f',
    storageBucket: 'ques-9e59f.firebasestorage.app',
    iosBundleId: 'com.example.addQues',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_GtOV-iZICfrVa8u0UoJ_zQjUMSG9dg',
    appId: '1:671942974107:web:cc046d3bdf63566919443e',
    messagingSenderId: '671942974107',
    projectId: 'ques-9e59f',
    authDomain: 'ques-9e59f.firebaseapp.com',
    storageBucket: 'ques-9e59f.firebasestorage.app',
    measurementId: 'G-5WDEY78D08',
  );

}