

default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_app_distribution1 do
     sh "flutter clean"
     sh "flutter build apk --release"
     firebase_app_distribution(
     app: EVN["App_KEY"],
     firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
     android_artifact_type: "APK",
     android_artifact_path: "D:/add_ques/build/app/outputs/flutter-apk/app-release.apk",
     testers: "abdofekryasda@gmail.com",
     release_notes: "new release"
  )
  end

end
